[mypy]
plugins = mypy_django_plugin.main, mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "core.settings"

# Model fields require verbose annotations that add noise without value
[mypy-catalog.models]
ignore_errors = True
